" initial vim configuration

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" remove bell noise
set visualbell

" switches on syntax highlighting
syntax enable

" set underline for current line
set cursorline

" change the default color scheme
colorscheme slate

" display line numbers
set number

" allow use of detecting file types
" trigger the FileType event
" set options based on this
" see http://vimdoc.sourceforge.net/htmldoc/filetype.html
filetype plugin indent on
" used in combination with ex:
autocmd FileType ruby setlocal sw=2 ts=2 expandtab
autocmd FileType javascript setlocal sw=2 ts=2 expandtab

" 1 tab = 4 spaces
" number of spaces for each step of auto indent
set shiftwidth=4
" number of spaces that tab counts for
set tabstop=4

" copy the indentation from the previous line, when starting a new line
set autoindent
" inserts one extra level of indentation in some cases
set smartindent
" indent '}' correctly
set smarttab

" always display status line
set laststatus=2
" print the current full file path in status
set statusline+=%f\ %y

" add code folding settings
"folding settings
set foldmethod=syntax   "fold based on syntax 
set nofoldenable        "dont fold by default
nnoremap <Space> za
vnoremap <Space> za

" moving around after helpgrep + vimgrep
nmap <silent> <RIGHT> :cnext<CR>
nmap <silent> <RIGHT><RIGHT> :cnfile<CR><C-G>
nmap <silent> <LEFT> :cprev<CR>
nmap <silent> <LEFT><LEFT> :cpfile<CR><C-G>

" look ahead to match a search pattern
set incsearch

" add pathogen
execute pathogen#infect()

" map nerdtree toggle
nmap <silent> <c-n> :NERDTreeToggle<CR>
