#!/usr/bin/env bash
#
# script to initialize osx development env.

# variables: modify to your desire
dir=$(pwd)
# brew packages to install
packages=(go gradle hub maven mongodb mysql node tmux wget)
# todo: just loop through files in dotfiles folder
dotfiles=(gitconfig gitignore vimrc zshrc)

section(){
  printf "\n\033[1;4m$1:\033[24m\n"
}
success(){
  printf "\033[1;32m$1\033[39m \n"
}
info(){
  printf "\033[1;36m$1\033[39m \n"
}
alert(){
  printf "\033[1;31m$1\033[39m \n"
}
danger(){
  printf "\033[1;33m$1\033[39m \n"
}

section "Creating symlinks for dotfiles"
# create symlinks for dotfiles
for file in "${dotfiles[@]}"; do
  danger "Creating symlink to .$file in home directory."
  # use pwd
  ln -si $dir/dotfiles/$file ~/.$file
done

# install rvm + stable ruby
section "Installing rvm + stable ruby"
if ! type "rvm" > /dev/null;
  then
  curl -sSL https://get.rvm.io | bash -s stable --ruby
else
  info "rvm already installed"
fi

# install brew packages w/ array arguement
install_packages(){
  if ! [ -z "$1" ];
    section "Installing brew packages"
    then
    # loop through an package array
    for package in "${packages[@]}";
    do
      # determine if installed
      installed=`brew ls --versions $package`
      if [[ -z "$installed" ]];
        then
        # installing uninstalled package
        success "Installing brew package: $package"
        brew install $package
      else
        info "$package already installed"
      fi
    done
  fi
}

# install brew
section "Installing homebrew"
# test that we're on osx
if [ "$(uname -s)" == "Darwin" ];
  then
  # determine if brew is installed
  if ! type "brew" > /dev/null;
    then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    info "brew already installed"
  fi
  # install any brew packages
  install_packages packages
fi

# install zsh + oh-my-zsh
section "Installing zsh + oh-my-zsh"
# test to see if we have zsh installed
if ! type "zsh" > /dev/null;
  then
  alert "please install zsh and re-run script"
else
  info "zsh already installed"
  # test if we have oh-my-zsh installed
  if [ ! -d ~/.oh-my-zsh/ ]; then
    # -c tell if file is true or not
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  else
    info "oh-my-zsh already installed"
  fi
fi
