#!/usr/bin/env bash
#
# script to initialize osx development env.
# source other files
source script/util
source script/osx
# variables: modify to your desire
dir=$(pwd)
# brew packages to install
packages=(go gradle hub maven macvim mongodb mysql node tmux wget caskroom/cask/brew-cask)
# software to install
casks=(atom dropbox flux firefox gitx iterm2 spectacle transmission virtualbox vlc)

section "Creating symlinks for dotfiles"
# add any symlink any file in dotfiles/
for file in dotfiles/*; do
  danger "Creating symlink with $file"
  # use pwd for correct directory
  ln -si $dir/$file ~/.${file#*/}
done

# install rvm + stable ruby
section "Installing rvm + stable ruby"
if ! type "rvm" > /dev/null;
  then
  curl -sSL https://get.rvm.io | bash -s stable --ruby
else
  info "rvm already installed"
fi

# install brew packages w/ array arg.
install_packages(){
  if ! [ -z "$1" ];
    section "Installing brew packages"
    then
    # loop through an package array
    for package in "${packages[@]}";
    do
      # determine if installed
      installed=`brew ls --versions $package`
      if [[ -z "$installed" ]];
        then
        # installing uninstalled package
        success "Installing brew package: $package"
        brew install $package
      else
        info "$package already installed"
      fi
    done
  fi
}

# install casks w/ array arg.
install_casks(){
  if ! [ -z "$1" ];
    section "Installing brew casks"
    then
    # loop through an package array
    for cask in "${casks[@]}";
    do
	  # TODO: determine if installed or not
      brew cask install --appdir=/my/path $cask
      # # determine if installed
      # installed=`brew ls --versions $package`
      # if [[ -z "$installed" ]];
      #   then
      #   # installing uninstalled package
      #   success "Installing brew package: $package"
      #   brew install $package
      # else
      #   info "$package already installed"
      # fi
    done
  fi
}
# install brew
section "Installing homebrew"
# test that we're on osx
if [ "$(uname -s)" == "Darwin" ];
  then
  # determine if brew is installed
  if ! type "brew" > /dev/null;
    then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    info "brew already installed"
  fi
  # install any brew packages
  install_packages packages
  install_casks casks
fi

# install zsh + oh-my-zsh
section "Installing zsh + oh-my-zsh"
# test to see if we have zsh installed
if ! type "zsh" > /dev/null;
  then
  alert "please install zsh and re-run script"
else
  info "zsh already installed"
  # test if we have oh-my-zsh installed
  if [ ! -d ~/.oh-my-zsh/ ]; then
    # -c tell if file is true or not
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  else
    info "oh-my-zsh already installed"
  fi
fi
