#!/usr/bin/env bash
#

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Set highlight color to green
defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"
