#!/usr/bin/env bash
#

section(){
  printf "\n\033[1;4m$1:\033[24m\n"
}
success(){
  printf "\033[1;32m$1\033[39m \n"
}
info(){
  printf "\033[1;36m$1\033[39m \n"
}
alert(){
  printf "\033[1;31m$1\033[39m \n"
}
danger(){
  printf "\033[1;33m$1\033[39m \n"
}
